// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_br333.Models;

namespace Mission06_br333.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    [Migration("20230212223017_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_br333.Models.FormResponse", b =>
                {
                    b.Property<int>("FormID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_to")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FormID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            FormID = 1,
                            Category = "Action/Adventure",
                            Director = "Denis Villaneuve",
                            Edited = false,
                            Lent_to = "Braden",
                            Notes = "My favorite movie.",
                            Rating = "PG-13",
                            Title = "Dune",
                            Year = (short)2021
                        },
                        new
                        {
                            FormID = 2,
                            Category = "Action/Adventure",
                            Director = "James Cameron",
                            Edited = false,
                            Lent_to = "Braden",
                            Notes = "My favorite new movie.",
                            Rating = "PG-13",
                            Title = "Avatar: The Way of Water",
                            Year = (short)2022
                        },
                        new
                        {
                            FormID = 3,
                            Category = "Action/Adventure",
                            Director = "James Cameron",
                            Edited = false,
                            Lent_to = "Braden",
                            Notes = "My favorite older movie.",
                            Rating = "PG-13",
                            Title = "Avatar",
                            Year = (short)2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
